### ISSUE TITLE
Missing code?

### ISSUE THREAD

**Issue by parenteaun** [herlo/polycule#1]
I just came across this repo via search. I don't see any code... Is this meant to be a project concept? Or is the code containerized on a separate branch and/or privately? The concept sounds really useful and if you've made any progress on it I'd love to see what you have.

**Comment by herlo** [comment]
> I just came across this repo via search. I don't see any code... Is this meant to be a project concept? Or is the code containerized on a separate branch and/or privately? The concept sounds really useful and if you've made any progress on it I'd love to see what you have.

At one time, I had aspirations of creating a bit of software to visually handle endpoints which could be represent a polycule, allowing individuals to design their own and display it somewhere online or on their personal environment. This never came to be anything more than a passing thought. I'm going to close out this repository and archive this issue.

Cheers!
